"""empty message

Revision ID: 05d96a1b6688
Revises: 4d0b55ae9f85
Create Date: 2021-03-08 23:23:15.703463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d96a1b6688'
down_revision = '4d0b55ae9f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alunos', sa.Column('sobrenome', sa.String(), nullable=True))
    op.add_column('professores', sa.Column('sobrenome', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professores', 'sobrenome')
    op.drop_column('alunos', 'sobrenome')
    # ### end Alembic commands ###
