"""empty message

Revision ID: 4d0b55ae9f85
Revises: e1b68653ce8c
Create Date: 2021-03-08 18:17:32.011635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0b55ae9f85'
down_revision = 'e1b68653ce8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('escolas', sa.Column('numero', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('escolas', 'numero')
    # ### end Alembic commands ###
